defaults:
  - paths: default
  - hydra: default
  - _self_

data:
  ra: 10000
  types: ["zero"] #["ppo", "random", "zero"]
  batch_size: 32
  horizon: 6
  shift: 6
  nr_episodes_train: 10 # this means all of them
  nr_episodes_val: 4
  nr_episodes_test: 4
  # Data efficiency settings
  num_workers: 2
  pin_memory: True
  persistent_workers: True

model:
  control_mask: False
  n_modes_width: 8
  n_modes_height: 8
  hidden_channels: 32
  in_channels: 3
  out_channels: 3
  lifting_channels: 16
  projection_channels: 16
  n_layers: 4

algo:
  lr: 3e-4
  epochs: 50

task_name: cfno