defaults:
  - paths: default
  - hydra: default
  - _self_

data:
  ra: 1000000
  batch_size: 64
  start_time: 200
  end_time: 400
  train_length: 15
  test_length: 60
  shift_time: 4
  stride_time: 0.5
  nr_episodes_train: 50
  nr_episodes_val: 10
  nr_episodes_test: 20
  # Data efficiency settings
  num_workers: 2
  pin_memory: True
  persistent_workers: True

model:
  n_modes_width: 16
  n_modes_height: 16
  n_modes_depth: 16
  hidden_channels: 32
  in_channels: 3
  out_channels: 3
  lifting_channels: 16
  projection_channels: 16
  n_layers: 4

algo:
  lr: 1e-3
  epochs: 400

task_name: fno3d