defaults:
  - paths: default
  - hydra: default
  - _self_

data:
  ra: 10000
  batch_size: 64
  start_time: 5
  end_time: 60
  length_input: 8
  length_target: 8
  shift_time: 4
  stride_time: 1
  nr_episodes_train: 100
  nr_episodes_val: 10
  nr_episodes_test: 20
  # Data efficiency settings
  num_workers: 4
  pin_memory: True
  persistent_workers: True

model:
  n_modes_width: 16
  n_modes_height: 16
  n_modes_depth: 16
  hidden_channels: 16
  in_channels: 3
  out_channels: 3
  lifting_channels: 16
  projection_channels: 16
  n_layers: 2

algo:
  lr: 1e-3
  epochs: 200

task_name: fno3d