defaults:
  - paths: default
  - hydra: default
  - _self_

data:
  ra: 2500
  batch_size: 32
  start: 1
  end: 101
  train_shift: 2
  test_shift: 8
  stride: 1
  test_length: 15
  nr_episodes_train: null # this means all of them
  nr_episodes_val: null
  nr_episodes_test: null
  # Data efficiency settings
  num_workers: 2
  pin_memory: True
  persistent_workers: True
  pressure: True

model:
  lr: 1e-3
  n_modes_width: 16
  n_modes_height: 16
  n_modes_depth: 16
  hidden_channels: 32
  in_channels: 6
  out_channels: 6
  lifting_channels: 16
  projection_channels: 16
  n_layers: 4

algo:
  epochs: 30

task_name: fno3d