defaults:
  - paths: default
  - hydra: default
  - _self_

task_name: test_fno3D
checkpoint: ${paths.model_dir}/fno3d_latest.ckpt

data:
  ra: 2500
  pressure: False
  batch_size: 4
  start: 300 # t=100
  end: 600 # t=300
  test_length: 100
  test_shift: 25
  stride: 1
  nr_episodes_train: null # this means all of them
  nr_episodes_val: null
  nr_episodes_test: null
  # Data efficiency settings
  num_workers: 0
  pin_memory: False
  persistent_workers: False
