defaults:
  - paths: default
  - hydra: default
  - _self_

data:
  ra: 2500
  batch_size: 8
  start: 100
  end: 300
  train_length: 10
  train_shift: 5
  test_length: 50
  test_shift: 25
  stride: 1
  nr_episodes_train: null # this means all of them
  nr_episodes_val: null
  nr_episodes_test: null
  # Data efficiency settings
  num_workers: 2
  pin_memory: True
  persistent_workers: True
  pressure: False

model:
  lr: 1e-3
  n_modes_width: 16
  n_modes_height: 16
  n_modes_depth: 16
  hidden_channels: 32
  in_channels: 4
  out_channels: 4
  lifting_channels: 16
  projection_channels: 16
  n_layers: 4

algo:
  epochs: 50

task_name: fno3d